Repository lazar0169/vertex, pull requests merged in 2018-12, with the labels that each got.

#40 Update table aft / update filters
  languages/de/translations.json
  languages/en/translations.json
  languages/fr/translations.json
  languages/sr/translations.json
  mapper.json
  objects/aft/aft-filter.html
  objects/aft/aft-tab-content.html
  objects/notifications.html
  objects/pagination.html
  objects/tickets/tickets-filter.html
  objects/tickets/tickets-tab-content.html
  scripts/aft/aft-filters.js
  scripts/aft/aft.js
  scripts/application.js
  scripts/communication.js
  scripts/components/toggle.js
  scripts/form.js
  scripts/localization.js
  scripts/notifications.js
  scripts/table.js
  scripts/tickets/tickets-appearance.js
  scripts/tickets/tickets-filters.js
  scripts/tickets/tickets-max-value.js
  scripts/tickets/tickets-sms-settings.js
  styles/aft/aft-tabs.css
  styles/common.css
  styles/form.css
  styles/login.css
  styles/machines/details-bar.css
  styles/main-content.css
  styles/modify-spectre.css
  styles/pagination.css
  styles/plugins/plugins.css
  styles/table.css
  styles/tickets/tickets-tab-content.css
  styles/top-bar.css
  views/index.html
  views/main.html
Labels: bug, feature, update

#42 Update tables
  scripts/components/toggle.js
  scripts/table.js
  styles/main-content.css
  styles/table.css
Labels: update

#43 Update tables font
  scripts/communication.js
  scripts/table.js
  styles/table.css
Labels: update

#45 Update tables rows
  core/misc.js
  mapper.json
  objects/cancel-transaction.html
  scripts/table.js
  scripts/template-engine.js
  styles/cancel-transaction.css
  views/main.html
Labels: update

#46 Update tables cancel
  mapper.json
  objects/cancel-button.html
  scripts/table.js
  styles/cancel-button.css
  views/main.html
Labels: feature, update

#47 Bugfix table / table filters
  objects/aft/aft-tab-content.html
  objects/cancel-button.html
  objects/tickets/tickets-tab-content.html
  scripts/aft/aft-filters.js
  scripts/form.js
  scripts/table.js
  scripts/tickets/tickets-filters.js
  scripts/tickets/tickets.js
  styles/cancel-button.css
  styles/notifications.css
  styles/table.css
Labels: bug

#48 Feature malfunctions
  core/utility.css
  mapper.json
  objects/aft/aft-filter.html
  objects/aft/aft-tab-content.html
  objects/jackpot/add-jackpot-choose-machines/choose-machines-jackpot-buttons.html
  objects/jackpot/add-jackpot-choose-machines/choose-machines-jackpot-chosen-filter.html
  objects/jackpot/add-jackpot-choose-machines/choose-machines-jackpot-content.html
  objects/jackpot/add-new-jackpot/add-new-jackpot-content.html
  objects/jackpot/jackpot-animation-settings.html
  objects/jackpot/jackpot-filter.html
  objects/machines/details-bar.html
  objects/machines/edit-page.html
  objects/main-content.html
  objects/malfunctions/malfunctions-filter.html
  objects/malfunctions/malfunctions-info.html
  objects/malfunctions/malfunctions.html
  objects/sidebar.html
  objects/tickets/tickets-filter.html
  objects/tickets/tickets-tab-content.html
  objects/user-profile/user-edit-profile.html
  objects/user-profile/user-info-profile.html
  scripts/aft/aft-filters.js
  scripts/components/dropdown-date.js
  scripts/malfunctions/malfunctions.js
  scripts/router.js
  scripts/sidebar.js
  scripts/tickets/tickets-filters.js
  scripts/top-bar.js
  scripts/user-profile.js
  styles/aft/aft-filters.css
  styles/components/dropdown.css
  styles/main-content.css
  styles/malfunctions/malfunctions.css
  styles/modify-spectre.css
  styles/table.css
  transpile.js
Labels: feature

#51 - Token not existing when creating top bar bug fix
  scripts/top-bar.js
Labels: bug

#53 Bugfix refresh token
  scripts/communication.js
  scripts/home.js
  scripts/login.js
Labels: bug

#54 Update AFT / Tickets
  core/utility.css
  fonts/OpenSans-Bold.ttf
  objects/aft/aft-tab-content.html
  scripts/aft/aft-filters.js
  scripts/communication.js
  scripts/tickets/tickets-filters.js
  styles/fonts.css
  styles/form.css
  styles/table.css
  styles/top-bar.css
Labels: bug, update
