Repository lazar0169/vertex, pull requests merged in 2018-10, with the labels that each got.

#10 Feature session
  .htaccess
  core/utility.js
  objects/preloader.html
  scripts/communication.js
  scripts/login.js
  scripts/router.js
  scripts/session.js
  views/index.html
  views/main.html
Labels: feature

#13 Update sidebar
  mapper.json
  objects/main-content.html
  scripts/application.js
  scripts/data.js
  scripts/machines.js
  scripts/router.js
  scripts/session.js
  scripts/sidebar.js
  scripts/template-engine.js
Labels: update

#12 Feature application
  objects/main-content.html
  scripts/router.js
  scripts/sidebar.js
Labels: feature

#14 Bugfix sidebar
  scripts/notifications.js
  scripts/sidebar.js
Labels: bug

#16 Feature notifications
  mapper.json
  objects/notifications.html
  scripts/application.js
  scripts/communication.js
  scripts/login.js
  scripts/notifications.js
  scripts/router.js
  scripts/session.js
  scripts/template-engine.js
  styles/notifications.css
  views/index.html
Labels: feature

#15 Feature components
  mapper.json
  objects/aft/aft-filter.html
  objects/aft/aft-tab-content.html
  objects/machines/edit-page.html
  objects/machines/machines-filter.html
  scripts/aft/aft-filter.js
  scripts/components/clear-dropdown-filter.js
  scripts/components/dropdown.js
  scripts/components/ms-dropdown.js
  scripts/data.js
  scripts/machines.js
  scripts/machines/edit-page.js
  scripts/machines/machines-filters.js
  scripts/sidebar.js
  styles/aft/aft-filter.css
  styles/components/dropdown.css
  styles/machines/edit-page.css
  styles/machines/machines-filters.css
  styles/machines/machines-table.css
  styles/sidebar.css
Labels: feature

#19 Feature preloader
  mapper.json
  scripts/casino.js
  scripts/communication.js
  scripts/home.js
  scripts/machines.js
  scripts/preloader.js
  scripts/router.js
  scripts/session.js
  styles/main-content.css
  styles/preloader.css
  views/index.html
  views/main.html
Labels: feature

#20 Feature tickets
  core/utility.css
  images/barcode.png
  mapper.json
  objects/aft/aft-filter.html
  objects/aft/aft-tab-content.html
  objects/aft/aft-tabs.html
  objects/main-content.html
  objects/tickets/tickets-filter.html
  objects/tickets/tickets-tab-content.html
  objects/tickets/tickets-tabs.html
  objects/tickets/tickets.html
  scripts/tickets/tickets-appearance.js
  scripts/tickets/tickets-filters.js
  styles/aft/aft-filter.css
  styles/aft/aft-tabs.css
  styles/components/dropdown.css
  styles/modify-spectre.css
  styles/tickets/tickets-appearance.css
  styles/tickets/tickets-tabs.css
  views/main.html
Labels: feature

#21 Bugfix sidebar
  scripts/sidebar.js
Labels: bug

#23 Feature topbar
  images/jiza.jpg
  mapper.json
  objects/main-content.html
  objects/top-bar.html
  objects/user-profile/user-edit-profile.html
  objects/user-profile/user-info-profile.html
  objects/user-profile/user-profile.html
  scripts/sidebar.js
  scripts/top-bar.js
  scripts/user-profile.js
  styles/index.css
  styles/main-content.css
  styles/modify-spectre.css
  styles/top-bar.css
  styles/user-profile/user-edit-profile.css
  styles/user-profile/user-info-profile.css
  styles/user-profile/user-profile-page.css
  views/main.html
Labels: feature

#24 Update localization
  scripts/template-engine.js
Labels: update

#25 Update communication
  objects/top-bar.html
  scripts/aft/aft-filter.js
  scripts/communication.js
  scripts/components/ms-dropdown.js
  scripts/sidebar.js
  scripts/top-bar.js
  styles/components/dropdown.css
  styles/machines/details-bar.css
  styles/tickets/tickets-appearance.css
Labels: update
